services:
  dbt:
   image: xemuliam/dbt:snowflake
   container_name: dbt_snowflake
   volumes:
    - .:/app
   working_dir: /app
   stdin_open: true
   tty: true
   command: sleep infinity
   environment:
    DBT_SNOWFLAKE_ACCOUNT: $(SNOWFLAKE_ACCOUNT)
    DBT_SNOWFLAKE_USER: $(SNOWFLAKE_USER)
    DBT_SNOWFLAKE_PASSWORD: $(SNOWFLAKE_PASSWORD)
    DBT_SNOWFLAKE_WAREHOUSE: $(SNOWFLAKE_WAREHOUSE)
    DBT_SNOWFLAKE_DATABASE: $(SNOWFLAKE_DATABASE)
    #DBT_SNOWFLAKE_SCHEMA: your_schem