services:
  dbt:
   image: xemuliam/dbt:snowflake
   container_name: dbt_snowflake
   volumes:
    - .:/app
    - ./.dbt:/root/.dbt
   working_dir: /app
   stdin_open: true
   tty: true
   command: bash -c "apt update && apt install -y git && git config --global --add safe.directory /app && sleep infinity
   